export default {
	extends: [
		'stylelint-config-recommended',
		'stylelint-config-standard-scss',
		'stylelint-config-standard-vue',
	],
	plugins: ['stylelint-order'],
	ignoreFiles: ['experiment/css/jquery-ui.css'],
	rules: {
		'selector-id-pattern': null,
		'selector-class-pattern': null,
		'no-descending-specificity': null, // should be fixed in the future
		'order/properties-order': [
			{
				properties: [
					'display',
					'position',
					'float',
					'top',
					'right',
					'bottom',
					'left',
					'z-index',
					'width',
					'height',
					'max-width',
					'max-height',
					'min-width',
					'min-height',
					'padding',
					'margin',
					'overflow',
					'clip',
					'clear',
					'font',
					'color',
					'text-align',
					'text-decoration',
					'background',
					'border',
					'border-radius',
					'opacity',
					'visibility',
					'transform',
				],
				unspecified: 'bottomAlphabetical',
			},
		],
	},
};
