name: GitHub Pages CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: echo "Running tests..." 

      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install linting dependencies
        run: |
          npm install htmlhint stylelint stylelint-config-standard eslint @eslint/js

      - name: Run HTML Validation
        run: npx htmlhint  '**/*.html'
        continue-on-error: false

      - name: Fix HTML Issues
        run: echo "HTMLHint does not support auto-fixing"

      - name: Run CSS Validation
        run: npx stylelint '**/*.css' 
        continue-on-error: false

      - name: Fix CSS Issues
        run: npx stylelint --fix '**/*.css' 

      - name: Run JavaScript Linting
        run: npx eslint .
        continue-on-error: false

      - name: Fix JavaScript Issues
        run: npx eslint --fix .

      - name: Commit and Push Fixes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b fix-lint-issues
          git add .
          git commit -m 'fix: auto-fix lint issues'
          git push origin fix-lint-issues

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'fix: auto-fix lint issues'
          branch: fix-lint-issues
          title: 'Auto-fix lint issues'
          body: 'This PR auto-fixes lint issues in HTML, CSS, and JavaScript files.'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Directory containing built files