name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install linting dependencies
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard eslint @eslint/js

      - name: Run HTML Validation
        run: htmlhint '**/*.html'
        continue-on-error: false

      - name: Fix HTML Issues
        run: echo "HTMLHint does not support auto-fixing"

      - name: Run CSS Validation
        run: stylelint '**/*.css'
        continue-on-error: false

      - name: Fix CSS Issues
        run: stylelint --fix '**/*.css'

      - name: Run ESLint
        run: eslint '**/*.js'

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create and Push Fix Branch
        run: |
          git checkout -b fix-lint-issues
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m 'fix: auto-fix lint issues'
            git pull --rebase origin fix-lint-issues
            git push origin fix-lint-issues
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'fix: auto-fix lint issues'
          branch: fix-lint-issues
          base: main
          title: 'Auto-fix lint issues'
          body: 'This PR auto-fixes lint issues in HTML, CSS, and JavaScript files.'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Directory containing built files